name: fetch
on:
  workflow_dispatch:
    inputs:
      channel_url:
        description: "Amazon Music channel URL (override)"
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: |
          npm ci || npm i
          npm run pw:install

      - name: Get first card info (URL & Title)
        id: first
        env:
          CHANNEL_URL: ${{ inputs.channel_url != '' && inputs.channel_url || vars.CHANNEL_URL }}
        run: |
          : "${CHANNEL_URL:=${{ vars.CHANNEL_URL }}}"
          INFO=$(CHANNEL_URL="$CHANNEL_URL" node amz_first_card_info.js)
          echo "$INFO" | tee first_card.json
          # jq が無い環境でも簡易抽出（行末の " を削る程度）
          EP_URL=$(node -e "console.log(JSON.parse(process.argv[1]).episode_url||'')" "$INFO")
          TITLE=$(node -e "console.log(JSON.parse(process.argv[1]).title||'')" "$INFO")
          echo "episode_url=$EP_URL" >> "$GITHUB_OUTPUT"
          echo "title=$TITLE" >> "$GITHUB_OUTPUT"

      - name: Summary
        run: |
          echo "### First card (URL & Title)" >> $GITHUB_STEP_SUMMARY
          echo "\n**URL**" >> $GITHUB_STEP_SUMMARY
          echo "\n\`\`\`\n${{ steps.first.outputs.episode_url }}\n\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "\n**Title**" >> $GITHUB_STEP_SUMMARY
          echo "\n\`\`\`\n${{ steps.first.outputs.title }}\n\`\`\`" >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        with:
          name: first-card
          path: first_card.json
