name: fetch
on:
  workflow_dispatch:
    inputs:
      channel_url:
        description: "Amazon Music channel URL (override)"
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: |
          npm ci || npm i
          npm run pw:install

      - name: Get first card URL only
        id: first
        env:
          CHANNEL_URL: ${{ inputs.channel_url != '' && inputs.channel_url || vars.CHANNEL_URL }}
        run: |
          : "${CHANNEL_URL:=${{ vars.CHANNEL_URL }}}"
          URL=$(CHANNEL_URL="$CHANNEL_URL" node amz_first_card_url.js)
          echo "$URL" | tee episode_url.txt
          echo "episode_url=$URL" >> "$GITHUB_OUTPUT"

      - name: Summary
        run: |
          echo "### First card URL" >> $GITHUB_STEP_SUMMARY
          echo "\n\`\`\`\n${{ steps.first.outputs.episode_url }}\n\`\`\`" >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        with:
          name: episode-url
          path: episode_url.txt
