name: AmazonMusic First Card URL

on:
  schedule:
    # 例: 毎日 JST 14:15 に実行（JST=UTC+9 → UTC 05:15）
    - cron: "15 5 * * *"
  workflow_dispatch:
    inputs:
      channel_url:
        description: "Amazon Music channel URL (override)"
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm ci || npm i
          npm run pw:install

      - name: Get Episode URL
        id: geturl
        env:
          # 既定はリポジトリ変数または下のデフォルト値を使用
          CHANNEL_URL: ${{ inputs.channel_url != '' && inputs.channel_url || vars.CHANNEL_URL }}
        run: |
          : "${CHANNEL_URL:=${{ vars.CHANNEL_URL }}}"
          if [ -z "$CHANNEL_URL" ]; then
            echo "CHANNEL_URL not provided"; exit 1
          fi
          URL=$(CHANNEL_URL="$CHANNEL_URL" node amz_first_card_url.js)
          echo "episode_url=$URL" >> "$GITHUB_OUTPUT"
          echo "$URL" > episode_url.txt
        
      - name: Probe with curl (headers & final URL)
        id: curlprobe
        env:
          CHANNEL_URL: ${{ inputs.channel_url != '' && inputs.channel_url || vars.CHANNEL_URL }}
        run: |
          : "${CHANNEL_URL:=${{ vars.CHANNEL_URL }}}"
          if [ -z "$CHANNEL_URL" ]; then echo "CHANNEL_URL not provided"; exit 1; fi

          UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
          # レスポンスヘッダ
          curl -I -A "$UA" -H "Accept-Language: ja,en;q=0.8" -sS "$CHANNEL_URL" | tee curl_headers.txt

          # リダイレクトを追って最終URL/コード
          curl -Ls -o /dev/null -w "final_url=%{url_effective}\nstatus=%{http_code}\n" -A "$UA" -H "Accept-Language: ja,en;q=0.8" "$CHANNEL_URL" | tee curl_final.txt

          # ボディ先頭だけ（サインイン/アクセス拒否の文言を掴む）
          curl -Ls -A "$UA" -H "Accept-Language: ja,en;q=0.8" "$CHANNEL_URL" | head -c 5000 > curl_body_snippet.txt || true

      - name: Summarize
        run: |
          echo "### Episode URL" >> $GITHUB_STEP_SUMMARY
          echo "\n\`\`\`\n${{ steps.geturl.outputs.episode_url }}\n\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: episode-url
          path: episode_url.txt

    # 同時実行制御（最新のみ動かす）
    concurrency:
      group: amazon-music-url
      cancel-in-progress: true
